
"""
Full Multi-Agent Research System

This module integrates all components of the research system:
- User clarification and scoping
- Research brief generation
- Multi-agent research coordination
- Final report generation
- Subtopic report evaluation and generation

The system orchestrates the complete research workflow from initial user
input through final report delivery.

Model clients, the subtopic toggle, and file-write behaviour are resolved from
the per-run runtime context so concurrent API runs stay isolated (no global
writer model, no process-global subtopic config, no unconditional file writes).
"""

import asyncio
import random
import re
import string
from datetime import datetime
from typing_extensions import Literal

from langchain_core.messages import HumanMessage, SystemMessage
from langgraph.graph import StateGraph, START, END
from langgraph.types import Command

from deep_research.utils import get_today_str, extract_text_from_response
from deep_research.runtime import get_runtime
from deep_research import events as _events
from deep_research.state_scope import (
    AgentState,
    AgentInputState,
    GenerateSubtopicReport,
    EndSubtopicEvaluation
)
from deep_research.research_agent_scope import clarify_with_user, write_research_brief, write_draft_report
from deep_research.multi_agent_supervisor import supervisor_agent


def _emit(type_: str, *, phase: str | None = None, agent: str | None = None,
          iteration: int | None = None, **payload) -> None:
    get_runtime().observer.emit(type_, phase=phase, agent=agent, iteration=iteration, **payload)


def _writer_model():
    runtime = get_runtime()
    model = getattr(runtime, "_resilient_writer", None)
    if model is None:
        model = runtime.models.supervisor(max_tokens=40000)
        setattr(runtime, "_resilient_writer", model)
    return model


def _subtopic_model():
    runtime = get_runtime()
    model = getattr(runtime, "_resilient_subtopic_model", None)
    if model is None:
        subtopic_tools = [GenerateSubtopicReport, EndSubtopicEvaluation]
        model = runtime.models.supervisor(tools=subtopic_tools, max_tokens=40000)
        setattr(runtime, "_resilient_subtopic_model", model)
    return model


# ===== FINAL REPORT GENERATION =====

async def final_report_generation(state: AgentState):
    """
    Final report shim node.

    The report is written by the write_final_report node inside the supervisor
    subgraph (cache-friendly). This node only handles the aborted case, saves
    the report to disk, and returns it up to the graph.
    """
    runtime = get_runtime()
    cfg = runtime.config

    # Check if research was aborted by circuit breaker or consecutive failures
    if state.get("aborted", False):
        abort_reason = state.get("abort_reason") or "Research aborted (reason unknown)"
        if runtime.console_enabled:
            print("\n--- [NODE: final_report_generation] ---")
            print(f"[Final Report] SKIPPED — research was aborted: {abort_reason}")
        raise RuntimeError(f"Research aborted: {abort_reason}")

    runtime.check_cancelled()
    final_report_content = state.get("final_report", "")

    if runtime.console_enabled:
        print("\n--- [NODE: final_report_generation] ---")
        print(f"Final Report ({len(final_report_content)} chars)")
        print(f"Generated by: [MODE: {cfg.subagent_output_mode}]")

    # CLI file write behaviour is preserved when the run's config allows file
    # output. API runs (save_report_to_file=False / output_mode="none") never
    # write files here — the host persists via structured results/events.
    if cfg.save_report_to_file and cfg.files_enabled():
        # Unique suffix so concurrent runs never overwrite each other's file.
        stamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        code = "".join(random.choices(string.ascii_lowercase, k=3))
        filename = f"Final_Report_{get_today_str().replace(' ', '_').replace(',', '')}_{stamp}_{code}.md"
        with open(filename, "w", encoding="utf-8") as f:
            f.write(final_report_content)
        if runtime.console_enabled:
            print(f"[Final Report] Completed and saved: {filename}")

    return {
        "final_report": final_report_content,
        "messages": ["Here is the final report: " + final_report_content],
    }

# ===== SUBTOPIC EVALUATION NODE =====

def extract_research_topics_from_supervisor(supervisor_messages: list) -> list[str]:
    """
    Extract the research_topic prompts from research sub-agent tool calls.
    These represent what each sub-agent was asked to investigate.
    """
    research_topics = []
    for msg in supervisor_messages:
        if hasattr(msg, 'tool_calls') and msg.tool_calls:
            for tool_call in msg.tool_calls:
                if tool_call.get("name", "").startswith("Research"):
                    topic = tool_call.get("args", {}).get("research_topic", "")
                    if topic:
                        research_topics.append(topic)
    return research_topics

async def subtopic_evaluation(state: AgentState) -> Command[Literal["subtopic_generation", "__end__"]]:
    """
    Evaluates the final report to decide if any subtopic reports should be generated.
    Uses tools to request report generation.
    """
    runtime = get_runtime()
    runtime.check_cancelled()
    prompts = runtime.prompts
    final_report = state.get("final_report", "")
    research_brief = state.get("research_brief", "")
    supervisor_messages = state.get("supervisor_messages", [])

    # Extract research topics from supervisor's research sub-agent calls
    research_topics = extract_research_topics_from_supervisor(supervisor_messages)
    research_topics_str = "\n---\n".join([f"**Topic {i+1}:** {topic}" for i, topic in enumerate(research_topics)])

    if runtime.console_enabled:
        print("\n--- [NODE: subtopic_evaluation] ---")
        print(f"Context: Research Brief ({len(research_brief)} chars)")
        print(f"Context: Final Report ({len(final_report)} chars)")
        print(f"Context: Research Topics Found: {len(research_topics)}")

    subtopic_evaluation_prompt = prompts.get(
        "SUBTOPIC_EVALUATION_PROMPT",
        "Evaluate the final report and decide if subtopic reports are needed.\n"
        "Research brief: {research_brief}\nFinal report: {final_report}\n"
        "Topics: {research_topics}")
    system_message = subtopic_evaluation_prompt.format(
        research_brief=research_brief,
        final_report=final_report,
        research_topics=research_topics_str
    )

    _emit(_events.SUBTOPIC_GENERATION_STARTED, phase="subtopic", agent="subtopic_evaluation")

    # The subtopic model already has fallbacks and tools bound
    response = await _subtopic_model().ainvoke([
        SystemMessage(content=system_message),
        HumanMessage(content="Please evaluate the Final Report and decide if any subtopic reports are needed.")
    ])

    # Process tool calls
    pending_briefs = []
    should_end = False

    if response.tool_calls:
        for tool_call in response.tool_calls:
            if tool_call["name"] == "GenerateSubtopicReport":
                pending_briefs.append({
                    "title": tool_call["args"]["title"],
                    "generation_brief": tool_call["args"]["generation_brief"]
                })
            elif tool_call["name"] == "EndSubtopicEvaluation":
                should_end = True

    if pending_briefs:
        if runtime.console_enabled:
            print(f"[Subtopic Evaluation] {len(pending_briefs)} subtopic reports to generate.")
        return Command(
            goto="subtopic_generation",
            update={"pending_subtopic_briefs": pending_briefs}
        )
    else:
        if runtime.console_enabled:
            print("[Subtopic Evaluation] No subtopic reports needed.")
        return Command(goto=END)

# ===== SUBTOPIC GENERATION NODE =====

async def subtopic_generation(state: AgentState):
    """
    Generates subtopic reports based on pending briefs from evaluation.
    Uses the full research notes to create detailed reports.
    Runs all report generations in parallel for efficiency.
    """
    runtime = get_runtime()
    runtime.check_cancelled()
    prompts = runtime.prompts
    cfg = runtime.config
    pending_briefs = state.get("pending_subtopic_briefs", [])
    notes = state.get("notes", [])
    flat_notes = [extract_text_from_response(n) for n in notes]
    findings = "\n".join(flat_notes)

    if runtime.console_enabled:
        print("\n--- [NODE: subtopic_generation] ---")
        print(f"Context: Pending Briefs: {[b['title'] for b in pending_briefs]}")
        print(f"Context: Findings ({len(findings)} chars)")

    async def generate_single_report(brief: dict) -> dict:
        """Generate a single subtopic report."""
        if runtime.console_enabled:
            print(f"[Subtopic Generation] Starting: {brief['title']}")

        target_language = state.get("target_language") or cfg.target_language_fallback

        subtopic_generation_prompt = prompts.get(
            "SUBTOPIC_GENERATION_PROMPT",
            "Write a detailed subtopic report titled {subtopic_title}.\n{brief}\n\nNotes:\n{notes}")
        prompt = subtopic_generation_prompt.format(
            subtopic_title=brief["title"],
            generation_brief=brief["generation_brief"],
            notes=findings,
            target_language=target_language,
        )

        # Use resilient writer for subtopic generation
        response = await _writer_model().ainvoke([HumanMessage(content=prompt)])
        report_content = extract_text_from_response(response.content)

        # Create a safe filename and save to disk (CLI file behaviour)
        safe_title = re.sub(r'[^\w\s-]', '', brief["title"]).strip().replace(' ', '_')
        filename = f"Subtopic_Report_{safe_title}.md"

        if cfg.save_report_to_file and cfg.files_enabled():
            with open(filename, "w", encoding="utf-8") as f:
                f.write(report_content)
            if runtime.console_enabled:
                print(f"[Subtopic Generation] Completed and saved: {filename}")
        else:
            if runtime.console_enabled:
                print(f"[Subtopic Generation] Completed (not saved to file): {brief['title']}")

        return {
            "title": brief["title"],
            "content": report_content,
            "filename": filename if cfg.save_report_to_file and cfg.files_enabled() else None
        }

    # Run all report generations in parallel
    if runtime.console_enabled:
        print(f"[Subtopic Generation] Generating {len(pending_briefs)} reports in parallel...")
    generated_reports = await asyncio.gather(*[
        generate_single_report(brief) for brief in pending_briefs
    ])

    if runtime.console_enabled:
        print(f"[Subtopic Generation] All {len(generated_reports)} subtopic reports complete.")
    _emit(_events.SUBTOPIC_GENERATION_COMPLETED, phase="subtopic", agent="subtopic_generation",
          count=len(generated_reports))

    return {
        "secondary_reports": list(generated_reports),
        "pending_subtopic_briefs": []  # Clear pending briefs
    }


def _route_after_final_report(state: AgentState) -> Literal["subtopic_evaluation", "__end__"]:
    """Route to subtopic evaluation only when the run's config enables it."""
    if get_runtime().config.enable_subtopic_generation:
        return "subtopic_evaluation"
    return END


# ===== GRAPH CONSTRUCTION =====
# Build the overall workflow (nodes resolve config/models per-run at runtime).
deep_researcher_builder = StateGraph(AgentState, input_schema=AgentInputState)

# Add workflow nodes
deep_researcher_builder.add_node("clarify_with_user", clarify_with_user)
deep_researcher_builder.add_node("write_research_brief", write_research_brief)
deep_researcher_builder.add_node("write_draft_report", write_draft_report)
deep_researcher_builder.add_node("supervisor_subgraph", supervisor_agent)
deep_researcher_builder.add_node("final_report_generation", final_report_generation)
deep_researcher_builder.add_node("subtopic_evaluation", subtopic_evaluation)
deep_researcher_builder.add_node("subtopic_generation", subtopic_generation)

# Add workflow edges
deep_researcher_builder.add_edge(START, "clarify_with_user")
deep_researcher_builder.add_edge("write_research_brief", "write_draft_report")
deep_researcher_builder.add_edge("write_draft_report", "supervisor_subgraph")
deep_researcher_builder.add_edge("supervisor_subgraph", "final_report_generation")
deep_researcher_builder.add_conditional_edges(
    "final_report_generation", _route_after_final_report,
    {"subtopic_evaluation": "subtopic_evaluation", END: END},
)
deep_researcher_builder.add_edge("subtopic_generation", END)


def build_research_agent(checkpointer=None):
    """Compile the full research graph with an optional checkpointer.

    The API supplies its durable LangGraph checkpointer here; the standalone
    CLI uses an in-memory saver. Graph nodes read per-run config/models from
    the runtime context, so one compiled graph safely serves many runs.
    """
    return deep_researcher_builder.compile(checkpointer=checkpointer)


# Backwards-compatible module-level compiled graph (no checkpointer).
agent = deep_researcher_builder.compile()
